services:
  frontend:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "5173:80"  # Exposing port 80 from the container to port 5173 on the host
    environment:
      # VITE_API_BASE_URL: http://localhost:3000  # URL for the backend service
      VITE_API_BASE_URL: https://attendancebackend-esgpgtd6akfheqar.centralindia-01.azurewebsites.net

    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge
